services:
  web:
    build: .
    container_name: flask_container_uv
    ports:
      - "8000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      # 💡 注入容器內部的連線資訊：連向服務名稱 'db'，Port 走內部的 3306
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=cki101_user
      - DB_PASSWORD=user_password_here
      - DB_NAME=cki101_db
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mysql:8.4
    container_name: mysql_cki101
    ports:
      - "8625:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password_here
      MYSQL_DATABASE: cki101_db
      MYSQL_USER: cki101_user
      MYSQL_PASSWORD: user_password_here
    volumes:
      - ./db_data:/var/lib/mysql
    restart: unless-stopped
